options:
    maas-mode:
        type: string
        default: region
        description: Type of maas node. Valid options are, (region, rack, region+rack, all)
    install_sources:
        type: string
        default: ppa:maas/next
        description: Specify location of apt repo.  ppa works here.
    dbname:
        type: string
        default: maasdb
        description: Name of the database to use when related to PostgreSQL.
    maas-url:
        type: string
        default: 
        description: |
            URL that rack controllers connect get RPC information and deploying
            machines use for metadata, APT proxy, and DNS.
            .
            It is recommended to leave this unset. In a multi unit deployment the
            maas_url in the regiond.conf will be set to the leader unit for the
            service unless this is set to override that value.
    admin-username:
        type: string
        default: admin
        description: Username for the initial admin user.
    admin-email:
        type: string
        default: noreply@maas
        description: Email for the initial admin user.
    admin-password:
        type: string
        default: maasadmin
        description: |
            Password for the initial admin user. If not set admin user will not be
            created.
    admin-ssh-import:
        type: string
        default:
        description: Import ssh public key from github or launchpad.
    # maas-name:
    #     type: string
    #     default:
    #     description: Name to identify this MAAS deployment.
    # main-archive:
    #     type: string
    #     default: http://archive.ubuntu.com/ubuntu
    #     description: |
    #         Ubuntu archive used by machines to retrieve packages for Intel
    #         architectures.
    # ports-archive:
    #     type: string
    #     default: http://ports.ubuntu.com/ubuntu-ports
    #     description: |
    #         Ubuntu archive used by machines to retrieve packages for non-Intel
    #         architectures.
    # enable-http-proxy:
    #     type: boolean
    #     default: !!bool true
    #     description: |
    #         Enable the use of an APT and HTTP/HTTPS proxy.
    #         .
    #         Provision machines to use the built-in HTTP proxy (or user specified
    #         proxy) for APT. MAAS also uses the proxy for downloading boot images.
    # http-proxy:
    #     type: string
    #     default: 
    #     description: |
    #         Proxy for APT and HTTP/HTTPS.
    #         .
    #         This will be passed onto provisioned machines to use as a proxy for APT
    #         traffic. MAAS also uses the proxy for downloading boot images. If no
    #         URL is provided, the built-in MAAS proxy will be used.
    # upstream-dns:
    #     type: string
    #     default:
    #     description: |
    #         Upstream DNS used to resolve domains not managed by this MAAS
    #         (space-separated IP addresses).
    # dnssec-validation:
    #     type: string
    #     default: auto
    #     description: |
    #         Enable DNSSEC validation of upstream zones.
    #         .
    #         Only used when MAAS is running its own DNS server. This value is used as
    #         the value of 'dnssec_validation' in the DNS server config.
    # ntp-server:
    #     type: string
    #     default: ntp.ubuntu.com
    #     description: |
    #         Address of NTP server for machines.
    #         .
    #         NTP server address passed to machines via a DHCP response.
    # default-storage-layout:
    #     type: string
    #     default: flat
    #     description: |
    #         Storage layout that is applied to a machine when it is commissioned.
    #         (Supports: flat, vlm, or bcache).
    # enable-disk-erasing-on-release:
    #     type: boolean
    #     default: !!bool false
    #     description: |
    #         Erase machines' disks prior to releasing.
    # curtin-verbose:
    #     type: boolean
    #     default: !!bool false
    #     description: |
    #         Turn on curtin verbose logging when a machine is being deployed.
    #         Installation log for the deployed or failed deployed machine will contain
    #         detailed log information to aid in bug reporting and development.
    # haproxy-stats-enabled:
    #     type: boolean
    #     default: !!bool false
    #     description: Enable the stats endpoint on the haproxy.
    # haproxy-stats-uri:
    #     type: string
    #     default: /haproxy?stats
    #     description: URI for the stats endpoint.
    # haproxy-stats-auth:
    #     type: string
    #     default: ubuntu:ubuntu
    #     description: |
    #         HTTP authentication to access the stats endpoint.
    #         .
    #         Accepts a multiple user password combinations. Each user password
    #         combination should be seperated by a ';'. Example:
    #         .
    #             ubuntu:ubuntu;ubuntu1:ubuntu1
    #         .
    #         Setting to an empty string will result in no authentication.
